baseURL = 'https://blogcube.netlify.app/'
languageCode = 'en-us'
title = 'Lama dev blog'

[pagination]
  pagerSize = 3

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"
    lineNos = true
    
