baseURL = 'https://blogcube.netlify.app/'
languageCode = 'en-us'
title = 'Lama dev blog'

[pagination]
  pagerSize = 5

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"
    lineNos = false
    
[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "SearchIndex"]
