baseURL = 'https://mahikumawat121998.github.io/hugo-blog-app/'
languageCode = 'en-us'
title = 'Lama dev blog'
relativeURLs = true
[pagination]
  pagerSize = 3

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"