name: Deploy Hugo to S3

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo

      - name: Deploy to S3
        run: aws s3 sync public/ s3://blog-cube-website
        env:
          AWS_ACCESS_KEY_ID: AKIAUDA2QLPBTWAFJYJ2
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: ap-south-1
          
